### PR TITLE
Fix for ESP8266 & DS1820 in parsite mode

### PR DESCRIPTION
**Pull request by wstrzalka**
This fix is silly but without it the ESP8266 is not able to power up DS1820 in parasite mode according to datasheet

### CODE REVIEW

**Comment by pezinek** [comment]
Well this fix isn't silly at all, it in fact reverts to original behaviour from pull request #30 that got corrupted by merge with pull request #10.

**Comment by wstrzalka** [comment]
Yes. But I still dont get how it fixes the issue :)

**Comment by milesburton** [comment]
Any final comments before I merge this?

**Comment by pezinek** [comment]
wstrzalka: It's easy, it fixes the issue because function getResolution calls function isConnected and that function uses the bus and thus disrupts the meassurement initiated earlier by  _wire->write(STARTCONVO, parasite); By replacing the getResolution call by cached bitResolution that has been obtained before STARTCONVO, we avoid this disruption. ;-)

**Comment by wstrzalka** [comment]
True - I missed the fact isConnected does actual communication.

**Pull request merged**
