### PR TITLE
Arduino nano compatibility

### PR DESCRIPTION
**Pull request by pieisgood**
Single line change to avoid issues on arduino nano (the cheap ones from amazon) at compile time.

### CODE REVIEW

**Comment by pieisgood** [comment]
This is for the Elegoo version of the arduino nano, they're super cheap so I think they're pretty common.

**Comment by RobTillaart** [comment]
- minor typo in the comment, "versions"
I do not understand you need it as the default of that **bool** is true. 
At least it is in the wire lib that is provided here.
Can you check the default value of the bool in the Onewire lib you use?

**Comment by pieisgood** [comment]
That's the thing though, the compilation on this version of the arduino nano does not recognize the default value and throws a compile time error. Since the value is being set to true anyway in this particular instance of search this change shouldn't affecting any other arduino versions but does make it compatible with this nano version.

**Comment by RobTillaart** [comment]
OK makes sense. One more question, are you using latest IDE/compiler version?
If not could you check if latest has same problem?

**Comment by pieisgood** [comment]
Well holy shit. Moving from version 1.8.4 to 1.8.5 fixed the issue in the compiler. That's voodoo. Especially considering there's nothing about it in their release notes https://www.arduino.cc/en/Main/ReleaseNotes

**Comment by RobTillaart** [comment]
So issue solved?

**Comment by pieisgood** [comment]
Guess so

**Pull request closed without merging**
