### PR TITLE
added CMakeLists.txt for use under ESP-IDF

### PR DESCRIPTION
**Pull request by diplfranzhoepfinger**
see https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html

### CODE REVIEW

**Comment by RobTillaart** [comment]
Interesting addition for a vertical market.
Does not interfere with anything of the code so no risks imho

@diplfranzhoepfinger 
Can you add some comments in the file?  meta info / header?

Thinking of this.
```
# Author: diplfranzhoepfinger 
# reference:  https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html
# URL: https://github.com/milesburton/Arduino-Temperature-Control-Library
# DATE: 
...
```

**Comment by RobTillaart** [comment]
LGTM

**Comment by milesburton** [comment]
> LGTM

I had to google that Rob!

**Comment by diplfranzhoepfinger** [comment]
> I had to google that Rob!

who is Rob ?

**Comment by milesburton** [comment]
@diplfranzhoepfinger Ah sorry, I was referring to @RobTillaart and his use of 'LGTM' of which I've never seen before :)

**Pull request merged**
