### PR TITLE
Added ability to specify external strong pullup driver pin

### PR DESCRIPTION
**Pull request by wstrzalka**
As per DS18B20 specification for two operations - scratchpad copy & temperature conversion strong pullup is required on the bus when in parasite mode. 
Although standard 4k7 resistor is usually enough with single device on 5V supply, this becomes a must when having more then one device or powering this up with 3V3. One of the workarounds used commonly is to ask for temperature conversion is asking devices one by one but it also not always work without playing with resistor value.

This enables requesting for temperature conversion on all devices at once on low voltage setups (eg. ESP8266 powered up by 3.3V) without even playing with pull-up resistor as per specification by setting additional P-MOSFET gate to low and those shortcuting the bus to the VCC for the time when high power demanding operation is executed.

The downside is extra pin is needed. This is made optional - if skipped the library behaves as before.

### CODE REVIEW

**Comment by milesburton** [comment]
Let me review this when I'm back in a couple of weeks

**Comment by mattdreimer** [comment]
This is interesting.  Just to clarify If I'm using this on an arduino with a fairly big one wire bus attached to say pin 6 then I could also attach pin7 to pin 6 (for example) pin7 would provide extra power to the bus when needed?  Right now I just play with the value of the resistor till I find one that works.

**Comment by mattdreimer** [comment]
I just gave this a try and could not get the example to work.  If I leave the pullup pin disconnected it works just fine. I have a one wire bus with parasite power.  Am I missing something??

**Comment by RobTillaart** [comment]
FYI
parasite power is also discussed here - https://github.com/milesburton/Arduino-Temperature-Control-Library/issues/54

**Comment by mattdreimer** [comment]
Its this pull request that I was trying.  When I make use of the external pull up I can't get the included example to work.  But it works as expected without the external pull up.  Both on a one wire bus in parasite power mode.  I thought that's what the external pull up was for?  I have the external pull up pin connected to the one wire bus pin

**Comment by vallon** [comment]
@mattdreimer The external pullup pin is supposed to control a MOSFET that that source +V to the bus.  You said you connected it directly.

Curiously, the DS18B20 Datasheet says 

> However, when the DS18B20 is performing temperature conversions or copying data from the scratchpad memory to EEPROM, the operating current can be as high as 1.5mA. This current can cause an unacceptable voltage drop across the weak 1-Wire pullup resistor and is more current than can be supplied by CPP. To assure that the DS18B20 has sufficient supply current, it is necessary to provide a strong pullup on the 1-Wire bus whenever temperature conversions are taking place or data is being copied from the scratchpad to EEPROM.

Note "necessary".  It appears to recommend against using parasite power without using an external strong pullup.

In any case, I think this would be better off in OneWire.  This is a bus issue, not a device issue.

At quick glance, you could change OneWire::write(data, parasite) to enable the strong pullup (instead of parasite), and depower() would turn it off.  Then, call depower() from DallasTemperature in the places you are deactivatingExternalPullup() (depower() should be called anyway after parasite cmds).

OneWire::enableExternalPullup(pin)
OneWire::disableExternalPullup()
OneWire::write(byte, paraste)
OneWire::depower()

**Comment by mattdreimer** [comment]
Thanks Vallon.  I see now.  In the pull request making external pull up pin low activates the pullup so it is driving the mosfet.  Which makes sense because after you are done with the pullup you do not want the one wire bus connected on that line at all so that you can read it as usual.  I'll give this another go and see what happens

**Comment by mmithril** [comment]
I vote for this merge request. It is indeed essential for my multi-sensor (and long-wire) network attached to ESP8266.

**Pull request closed without merging**
